# Generated by Django 4.0 on 2022-01-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('score', models.IntegerField()),
                ('memo', models.TextField(max_length=200)),
                ('suggest_id', models.CharField(choices=[('1', '非常不滿意'), ('2', '不滿意'), ('3', '普通'), ('4', '滿意'), ('5', '非常滿意')], default='5', max_length=1)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
