# Generated by Django 4.0 on 2022-01-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_person_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='account',
        ),
    ]
