# Generated by Django 4.0 on 2021-12-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='msg_email',
        ),
        migrations.RemoveField(
            model_name='msg',
            name='msg_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg_memo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg_score',
            field=models.IntegerField(null=True),
        ),
    ]
