# Generated by Django 4.0 on 2021-12-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0002_remove_msg_msg_email_remove_msg_msg_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='user_account',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
