# Generated by Django 4.0 on 2021-12-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_rename_user_account_msg_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='msg_memo',
            new_name='memo',
        ),
        migrations.RenameField(
            model_name='msg',
            old_name='msg_score',
            new_name='score',
        ),
    ]
