# Generated by Django 4.0 on 2021-12-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0006_remove_user_date_msg_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msg',
            options={'ordering': ['-date', '-user_id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-account', '-name']},
        ),
        migrations.AlterField(
            model_name='msg',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
