# Generated by Django 4.0 on 2021-12-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0007_alter_msg_options_alter_user_options_alter_msg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='score',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
