# Generated by Django 4.0 on 2021-12-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0008_alter_msg_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
