# Generated by Django 4.0 on 2021-12-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_user_date_alter_user_memo_alter_user_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(),
        ),
    ]
